dbsk/Models/StudentsModel.cs
using System.Data;
using MySql.Data.MySqlClient;


namespace dbsk7.Models
{
    public class StudentsModel
    {
        private string connectionString = "";

        public StudentsModel(string connectionName)
        {
            connectionString = System.Configuration.ConfigurationManager.ConnectionStrings[connectionName].ConnectionString;
        }

        public DataTable SearchStudents(string name, string studyProgram)
        {
            MySqlConnection dbcon = new MySqlConnection(connectionString);
            dbcon.Open();
            MySqlDataAdapter adapter = new MySqlDataAdapter("SELECT * FROM alien WHERE ID LIKE @name AND RaceName=@studyProgram;", dbcon);
            adapter.SelectCommand.Parameters.AddWithValue("@name", "%" + name + "%");
            adapter.SelectCommand.Parameters.AddWithValue("@studyProgram", studyProgram);
            DataSet ds = new DataSet();
            adapter.Fill(ds, "result");
            DataTable StudentsTable = ds.Tables["result"];
            dbcon.Close();
            return StudentsTable;
        }
    }
}

dbsk/Models/StudyProgramModel.cs
using MySql.Data.MySqlClient;
using System.Data;

namespace dbsk7.Models
{
    public class StudyProgramModel
    {
        private string connectionString = "";

        public StudyProgramModel()
        {
            connectionString = System.Configuration.ConfigurationManager.ConnectionStrings["wwwlab.iki.his.se-dbsk"].ConnectionString;
        }

        public DataTable GetAllAliens()
        {
            MySqlConnection dbcon = new MySqlConnection(connectionString);
            dbcon.Open();
            MySqlDataAdapter adapter = new MySqlDataAdapter("SELECT * FROM alien;", dbcon);
            DataSet ds = new DataSet();
            adapter.Fill(ds, "result");
            DataTable StudyProgramsTable = ds.Tables["result"];
            dbcon.Close();
            return StudyProgramsTable;
        }
        public DataTable GetAllStudyPrograms()
        {
            MySqlConnection dbcon = new MySqlConnection(connectionString);
            dbcon.Open();
            MySqlDataAdapter adapter = new MySqlDataAdapter("SELECT distinct RaceName FROM alien;", dbcon);
            DataSet ds = new DataSet();
            adapter.Fill(ds, "result");
            DataTable StudyProgramsTable = ds.Tables["result"];
            dbcon.Close();
            return StudyProgramsTable;
        }

        public DataTable GetAllDanger()
        {
            MySqlConnection dbcon = new MySqlConnection(connectionString);
            dbcon.Open();
            MySqlDataAdapter adapter = new MySqlDataAdapter("SELECT * FROM DangerLevel;", dbcon);
            DataSet ds = new DataSet();
            adapter.Fill(ds, "result");
            DataTable DangerTable = ds.Tables["result"];
            dbcon.Close();
            return DangerTable;
        }

        public void DeleteAlien(string ID, string RaceName)
        {
            MySqlConnection dbcon = new MySqlConnection(connectionString);
            dbcon.Open();
            string deleteString = "DELETE FROM alien WHERE ID=@ID AND RaceName=@RaceName;";
            MySqlCommand sqlCmd = new MySqlCommand(deleteString, dbcon);
            sqlCmd.Parameters.AddWithValue("@ID", ID);
            sqlCmd.Parameters.AddWithValue("@RaceName", RaceName);
            int rows = sqlCmd.ExecuteNonQuery();
            dbcon.Close();

        }

        public void InsertAlien(string ID, string RaceName, string Color, int Danger)
        {
            MySqlConnection dbcon = new MySqlConnection(connectionString);
            dbcon.Open();
            string insertString = "INSERT INTO alien(ID,Danger,RaceName,Color) VALUES(@ID,@Danger,@RaceName,@Color)";
            MySqlCommand sqlCmd = new MySqlCommand(insertString, dbcon);
            sqlCmd.Parameters.AddWithValue("@ID", ID);
            sqlCmd.Parameters.AddWithValue("@Danger", Danger);
            sqlCmd.Parameters.AddWithValue("@RaceName", RaceName);
            sqlCmd.Parameters.AddWithValue("@Color", Color);
            int rows = sqlCmd.ExecuteNonQuery();
            dbcon.Close();
        }
        public void UpdateDanger(string ID, int Danger)
        {
            MySqlConnection dbcon = new MySqlConnection(connectionString);
            dbcon.Open();
            string updateString = "CALL UPDATEDANGER(@alienID, @alienDanger)";
            MySqlCommand sqlCmd = new MySqlCommand(updateString, dbcon);
            sqlCmd.Parameters.AddWithValue("@alienID", ID);
            sqlCmd.Parameters.AddWithValue("@alienDanger", Danger);
            int rows = sqlCmd.ExecuteNonQuery();
            dbcon.Close();

        }

    } 
}


dbsk/Controllers/HomeController.cs
using System.Web.Mvc;

namespace dbsk7.Controllers
{
    public class HomeController : Controller
    {

        //
        // GET: /Home/

        public ActionResult Index()
        {
            ViewBag.SomeText = "Welcome to PUCKO";
            return View(); 
        }

    }
}

dbsk/Controllers/Page2Controller.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace dbsk7.Controllers
{
    public class Page2Controller : Controller
    {
        //
        // GET: /Page2/

        public ActionResult Index()
        {
            return View(new dbsk7.Models.StudyProgramModel().GetAllAliens());
        }

    }
}

dbsk/Controllers/Page3Controller.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using dbsk7.Models;

namespace dbsk7.Controllers
{
    public class Page3Controller : Controller
    {

        private StudentsModel sm = new StudentsModel("wwwlab.iki.his.se-dbsk");
        private StudyProgramModel sp = new StudyProgramModel();

        //
        // GET: /Page3/

        public ActionResult Index()
        {
            ViewBag.AllStudyProgramsTable = sp.GetAllStudyPrograms();
            return View();
        }

        //
        // GET: /Home/SearchStudents/{name}?studyProgram={studyProgram}

        public ActionResult SearchStudents(string name, string studyProgram)
        {
            ViewBag.SearchResults = sm.SearchStudents(name, studyProgram);
            return View();
        }

    }
}


dbsk/Controllers/Page4Controller.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using dbsk7.Models;

namespace dbsk7.Controllers
{
    public class Page4Controller : Controller
    {

        private StudentsModel sm = new StudentsModel("wwwlab.iki.his.se-dbsk");
        private StudyProgramModel sp = new StudyProgramModel();

        //
        // GET: /Page4/

        public ActionResult Index()
        {
            return View(new dbsk7.Models.StudyProgramModel().GetAllAliens());
        }

        public ActionResult DeleteAlien(string ID, string RaceName)
        {
            sp.DeleteAlien(ID,RaceName);
            return RedirectToAction("Index");
        }
    }
}

dbsk/Controllers/Page5Controller.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using dbsk7.Models;

namespace dbsk7.Controllers
{
    public class Page5Controller : Controller
    {

        private StudentsModel sm = new StudentsModel("wwwlab.iki.his.se-dbsk");
        private StudyProgramModel sp = new StudyProgramModel();

        //
        // GET: /Page5/

        public ActionResult Index()
        {
            ViewBag.DangerTable = sp.GetAllDanger();
            return View(new dbsk7.Models.StudyProgramModel().GetAllAliens());

        }

        public ActionResult InsertAlien(string ID, string RaceName, string Color, int Danger)
        {
            sp.InsertAlien(ID,RaceName,Color, Danger);
            return RedirectToAction("Index");
        }

    }
}

dbsk/Controllers/Page6Controller.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using dbsk7.Models;

namespace dbsk7.Controllers
{
    public class Page6Controller : Controller
    {

        private StudentsModel sm = new StudentsModel("wwwlab.iki.his.se-dbsk");
        private StudyProgramModel sp = new StudyProgramModel();

        //
        // GET: /Page6/

        public ActionResult Index()
        {
            ViewBag.DangerTable = sp.GetAllDanger();
            return View(new dbsk7.Models.StudyProgramModel().GetAllAliens());

        }

        public ActionResult UpdateDanger(string ID, int Danger)
        {
            sp.UpdateDanger(ID, Danger);
            return RedirectToAction("Index");
        }

    }
}

dbsk/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Index";
}

@section PageHeader {
    <h2>Home</h2>
}

<p>@ViewBag.SomeText</p>

@Html.ActionLink("List of aliens", "Index", "Page2")
@Html.ActionLink("Search", "Index", "Page3")
@Html.ActionLink("Delete", "Index", "Page4")
@Html.ActionLink("Insert", "Index", "Page5")
@Html.ActionLink("Update Danger", "Index", "Page6")

dbsk/Views/Page2/Index.cshtml
@using System.Data
@model DataTable

@{
    ViewBag.Title = "Page2";
}



<table border ="1">
    <tr>
        @foreach(DataColumn dataColumn in Model.Columns){
            string columnName = char.ToUpper(dataColumn.ColumnName[0]) + dataColumn.ColumnName.Substring(1);
            <th>@columnName</th> 
        }
    </tr>
    @foreach (DataRow studyProgramRow in Model.Rows)
    {
        <tr>
            @for (int i = 0; i < Model.Columns.Count; ++i)
            {
                <td>@studyProgramRow[i]</td>
            }
        </tr>
    }
</table>
@Html.ActionLink("Back to home", "Index", "Home")


@section PageHeader {
    <h2>List of all aliens</h2>
}

dbsk/Views/Page3/Index.cshtml
@using System.Data
@model DataTable

@{
    ViewBag.Title = "Page3";
}

<h2>Find student</h2>
<form method="post" action="@Url.Action("SearchStudents", "Page3")">
    <label>
        Name:
        <input type="text" name="name" value="" placeholder="Student name" />
    </label>
    <label>
        Study program:
        <select name="studyProgram">
            @foreach (var dr in ViewBag.AllStudyProgramsTable.Rows)
            {
                <option value="@dr["RaceName"]">@dr["RaceName"]</option>
            }
        </select>
    </label>
    <input type="submit" value="Search" />
</form>
@Html.ActionLink("Back to home", "Index", "Home")

dbsk/Views/Page3/SearchStudents.cshtml

@{
    ViewBag.Title = "Search result";
}

<h2>Search result</h2>
@if (ViewBag.SearchResults != null && ((System.Data.DataTable)ViewBag.SearchResults).Rows.Count > 0)
{
    <table border ="1">
        <tr>
            @foreach (var dataColumn in ViewBag.SearchResults.Columns)
            {
                <th>@dataColumn.ColumnName</th>
            }
        </tr>
        @foreach (var studentRow in ViewBag.SearchResults.Rows)
        {
            <tr>
                @for (int i = 0; i < ViewBag.SearchResults.Columns.Count; ++i)
                {
                    <td>@studentRow[i]</td>
                }

            </tr>
        }
    </table>
}
else
{
    <p>No search results found</p>
}

@Html.ActionLink("<-- Back", "Index", "Home", null, new { title = "Go back to search form" })

dbsk/Views/Page4/Index.cshtml
@using System.Data
@model DataTable

@{
    ViewBag.Title = "Page4";
}

<h2>Delete</h2>
<table border ="1">
    <tr>
        @foreach (DataColumn dataColumn in Model.Columns)
        {
            <th>@dataColumn.ColumnName</th>
        }
    </tr>
    @foreach (DataRow studyProgramRow in Model.Rows)
    {
        <tr>
            @for (int i = 0; i < Model.Columns.Count; ++i)
            {
                <td>@studyProgramRow[i]</td>
            }
            <td>
                @Html.ActionLink("Delete", "DeleteAlien", 
                    new { ID = studyProgramRow["ID"],RaceName = studyProgramRow["RaceName"] },
                    new { title = "Click to delete Alien " + studyProgramRow["ID"] })
            </td>
            </tr>
        }
    </table>
@Html.ActionLink("Back to home", "Index", "Home")

dbsk/Views/Page5/Index.cshtml
@using System.Data
@model DataTable

@{
    ViewBag.Title = "Page5";
}

<h2>Insert aliens</h2>

<form method="post" action="@Url.Action("InsertAlien", "Page5")">
    <label>
        Alien ID:
        <input type="text" name="ID" value="" placeholder="Insert ID.." />
        Alien Race:
        <input type="text" name="RaceName" value="" placeholder="Insert Race.." />
        Alien Color:
        <input type="text" name="Color" value="" placeholder="Insert color.." />
        Danger:
        <select name="Danger">
            @foreach (var dr in ViewBag.DangerTable.Rows)
            {
                <option value="@dr["DangerCode"]">@dr["DangerName"]</option>
            }
        </select>
    </label>
    <input type="submit" value="Insert" />
</form>


    <table border ="1">
        <tr>
            @foreach (DataColumn dataColumn in Model.Columns)
            {
                <th>@dataColumn.ColumnName</th>
            }
        </tr>
        @foreach (DataRow studyProgramRow in Model.Rows)
        {
            <tr>
                @for (int i = 0; i < Model.Columns.Count; ++i)
                {
                    <td>@studyProgramRow[i]</td>
                }
            </tr>
        }
    </table>
    @Html.ActionLink("Back to home", "Index", "Home")

dbsk/Views/Page6/Index.cshtml
@using System.Data
@model DataTable

@{
    ViewBag.Title = "Page6";
}

<form method="post" action="@Url.Action("UpdateDanger", "Page6")">
    <label>
        Alien ID:
        <input type="text" name="ID" value="" placeholder="Insert ID.." />
        Danger:
        <select name="Danger">
            @foreach (var dr in ViewBag.DangerTable.Rows)
            {
                <option value="@dr["DangerCode"]">@dr["DangerName"]</option>
            }
        </select>
    </label>
    <input type="submit" value="Update" />
</form>




<table border="1">
    <tr>
        @foreach (DataColumn dataColumn in Model.Columns)
        {
            string columnName = char.ToUpper(dataColumn.ColumnName[0]) + dataColumn.ColumnName.Substring(1);
            <th>@columnName</th>
        }
    </tr>
    @foreach (DataRow studyProgramRow in Model.Rows)
    {
        <tr>
            @for (int i = 0; i < Model.Columns.Count; ++i)
            {
                <td>@studyProgramRow[i]</td>
            }
        </tr>
    }
</table>
@Html.ActionLink("Back to home", "Index", "Home")


@section PageHeader {
    <h2>Update aliens</h2>
}

dbsk/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title>@ViewBag.Title</title>
    <link href="@Url.Content("~/Content/Site.css")" rel="stylesheet" type="text/css" />
</head>

<body>
    <header style="padding:5px 10px;background-color:#ccc">
        @RenderSection("PageHeader", false)
    </header>
    @RenderBody()
    @Html.Partial("_PageFooter")
    </body>
</html>

dbsk/Views/Shared/_PageFooter.cshtml
<footer style="background-color:#ccc;text-align:center;padding:15px;">
    


</footer>